### ISSUE TITLE
Cannot install gem from repository

### ISSUE THREAD

**Issue by skin-soc** [paul-sx/huginn_mattermost_urls_to_files#1]
`sudo gem install huginn_mattermost_urls_to_files -s https://github.com/paul-sx/huginn_mattermost_urls_to_files`

yields...

`Unable to download data from https://github.com/paul-sx/huginn_mattermost_urls_to_files/ - bad response Not Found 404 (https://github.com/paul-sx/huginn_mattermost_urls_to_files/specs.4.8.gz)`

**Comment by paul-sx** [comment]
I'm not sure how to set up the repo to work with that command, but here's other options to get it working.

### Try a `Gemfile`
```ruby
source 'https://rubygems.org'
gem 'huginn_mattermost_urls_to_files', git: 'https://github.com/paul-sx/mattermost_urls_to_files'
```
Then do `bundle install`
### Build and install the gem file
```bash
git clone https://github.com/paul-sx/huginn_mattermost_urls_to_files.git
cd huginn_mattermost_to_files
gem build huginn_mattermost_to_files.gemspec
gem install huginn_mattermost_to_files-0.1.gem
```
### Let Huginn do it when it comes up (`.env` file with docker compose)
```bash
ADDITIONAL_GEMS=huginn_mattermost_urls_to_files(git:https://github.com/paul-sx/huginn_mattermost_urls_to_files.git)
```

**Comment by skin-soc** [comment]
Thanks! Worked.
